version: '3.1'

services:
  db:
    container_name: mongoDB
    image: ${MONGODB_IMAGE:-mongo:4.2.1}
    restart: always
    volumes:
      - ./data:${HOME}/data/db
    environment:
      - MONGO_INITDB_DATABASE=numberwang
    ports:
      - 27017:27017

  mongo-express:
    image: ${MONGOEXPRESS_IMAGE:-mongo-express}
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_URL=${MONGO_URI:-mongodb://localhost:27017}
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - db
    restart: unless-stopped
    ports:
      - '8081:8081'
    depends_on:
      - db

  teamflash-bot:
    build:
      context: .
      dockerfile: ${ARMDockerfile:-Dockerfile}
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - db
    links:
      - db
volumes:
  data:
