version: '3.1'

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     - NODE_ENV=production
  #   working_dir: /app
  #   user: node
  #   volumes:
  #     - .:/app
  #   command: npm start
  #   depends_on:
  #     - db
  db:
    container_name: mongoDB
    image: mongo:4.2.1
    restart: always
    volumes:
      - ./data:${HOME}/data/db
    environment:
      - MONGO_INITDB_DATABASE=numberwang
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_URL=${MONGO_URI}
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - db
    restart: unless-stopped
    ports:
      - '8081:8081'
    depends_on:
      - db
volumes:
  data:
